workflows:
version: 2
build_accept_delpoy:
  jobs:
    - test:
      docker:
        - image: adambene/circleci-openjdk-awscli
      working_directory: ~/bootcamp-circle-cloudformation
      steps:
        - checkout
        - run: sbt test
    - deploy:
        docker:
          - image: adambene/circleci-openjdk-awscli
        working_directory: ~/bootcamp-circle-cloudformation
        steps:
           - run: build-and-deploy-to-aws.sh "GabrielScalingGroup" "gabrielPrefix"
        filters:
          branches:
            only:
              - master

